### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'birdview_v3_cache/Carla/Maps/Town03__px_per_meter=1__opendrive_hash=ec2989811f7481fc0c59c5132ffadaa8ba04102c__margin=300.npy.lock'

### ISSUE THREAD

**Issue by ADI201998** [deepsense-ai/carla_birdeye_view#11]
Hello,
I cloned this repo and installed it using this command :- `sudo python3 setup.py install`

When I copied the contents from the basic code useage into my code, I am getting this error:

```
pygame 2.0.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "carla_sync_test.py", line 228, in <module>
    main()
  File "carla_sync_test.py", line 141, in main
    birdview_producer = BirdViewProducer(
  File "/usr/local/lib/python3.8/dist-packages/carla_birdeye_view-1.1.1-py3.8.egg/carla_birdeye_view/__init__.py", line 166, in __init__
  File "/home/aditya/.local/lib/python3.8/site-packages/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/aditya/.local/lib/python3.8/site-packages/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/aditya/.local/lib/python3.8/site-packages/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: 'birdview_v3_cache/Carla/Maps/Town03__px_per_meter=1__opendrive_hash=ec2989811f7481fc0c59c5132ffadaa8ba04102c__margin=300.npy.lock'
```

**Comment by MotamedNia** [comment]
Hi, I've got the same error.
```
FileNotFoundError: [Errno 2] No such file or directory: 'birdview_v2_cache/Carla/Maps/Town10HD_Opt__px_per_meter=4__opendrive_hash=a49910ad5e7021976e6371dcf7feb34775ce84b2__margin=300.npy.lock'

```

**Comment by MotamedNia** [comment]
I have created directories `birdview_v2_cache/Carla/Maps` manually and the issue is solved!!
